#include <dzplugin.h>

#include "config.h"
#include "qmetaobjectbrowser.hpp"

DZ_PLUGIN_DEFINITION(PLUGIN_NAME);
DZ_PLUGIN_AUTHOR(PLUGIN_AUTHOR);
DZ_PLUGIN_VERSION(PLUGIN_VERSION_MAJOR, PLUGIN_VERSION_MINOR, PLUGIN_VERSION_REV, PLUGIN_VERSION_BUILD);
DZ_PLUGIN_DESCRIPTION(PLUGIN_DESCRIPTION);

DZ_PLUGIN_CLASS_GUID(OfQMetaObjectBrowserPane, C7EC4AEF-6146-4A3A-AF11-DC07EEAFF100);
DZ_PLUGIN_CLASS_GUID(OfQMetaObjectBrowserPaneAction, C7EC4AEF-6146-4A3A-AF11-DC07EEAFF101);
